
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Shreyash Haritashya
 */
public class NewBooking extends javax.swing.JFrame {

    /**
     * Creates new form NewBooking
     */
    public NewBooking() {
        initComponents();
        setCurrentLoginDetails();
        toggleEmployeeButton();
        getCustomerData();
    }
    
    public void setCurrentLoginDetails(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?autoReconnect=true&useSSL=false", "root", "aman123456");
            Statement st = con.createStatement();
            String r = "select emp_id from logged_in_hotel_id";
            ResultSet rs0 = st.executeQuery(r);
            if(rs0.next()){
                r = "select emp_name, is_admin, emp_id from employee where emp_id = '"+ rs0.getString("emp_id") +"'";
                ResultSet rs1 = st.executeQuery(r);
                if(rs1.next()){
                    if(rs1.getString("is_admin").equals("1")){
                        emp_name_label.setText("Admin Name -");
                    }
                    emp_name_detail.setText(rs1.getString("emp_name"));
                    emp_id_detail.setText(rs1.getString("emp_id"));
                }
            }
        } catch(Exception e){
            System.out.print(e);
        }

    }
    
    
    public void getCustomerData(){
        SubmitButton3.setVisible(false);
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?autoReconnect=true&useSSL=false", "root", "aman123456");
        Statement st = con.createStatement();
        String r = "select cust_id from logged_in_hotel_id where cust_id is not null";
        ResultSet rs0 = st.executeQuery(r);
        if(rs0.next()){
            String cust_id = rs0.getString("cust_id");
            String r1 = "select cust_fname from customer where cust_id = '"+ cust_id +"'";
            ResultSet rs1 = st.executeQuery(r1);
            if(rs1.next()){
               cust_name.setText(rs1.getString("cust_fname"));
               id.setText(cust_id); 
            }
        }
        } catch(Exception e) {
            System.out.print(e);
        }  
    }
    
    public void toggleEmployeeButton(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?autoReconnect=true&useSSL=false", "root", "aman123456");
            Statement st = con.createStatement();
            String r = "select emp_id from logged_in_hotel_id";
            ResultSet rs0 = st.executeQuery(r);
            if(rs0.next()){
                r = "select is_admin from employee where emp_id = '"+ rs0.getString("emp_id") +"'";
                ResultSet rs1 = st.executeQuery(r);
                if(rs1.next()){
                    if(rs1.getString("is_admin").equals("0")){
                        EmployeeButton.setEnabled(false);
                    }
                }
            }
        } catch(Exception e){
            System.out.print(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        AppIcon = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        HomeButton = new javax.swing.JButton();
        BookingButton = new javax.swing.JButton();
        CustomerButton = new javax.swing.JButton();
        PaymentButton = new javax.swing.JButton();
        EmployeeButton = new javax.swing.JButton();
        SubmitButton2 = new javax.swing.JButton();
        SubmitButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cust_name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        checkin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        checkout = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        num = new javax.swing.JComboBox();
        SubmitButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        SubmitButton3 = new javax.swing.JButton();
        emp_name_detail = new javax.swing.JLabel();
        emp_name_label = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        emp_id_detail = new javax.swing.JLabel();

        setTitle("New Booking ");
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1260, 720));

        topPanel.setBackground(new java.awt.Color(89, 95, 239));
        topPanel.setAlignmentX(0.0F);
        topPanel.setAlignmentY(0.0F);

        AppIcon.setBackground(new java.awt.Color(255, 255, 255));
        AppIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjHoteliers/Images/AppIcon.jpg"))); // NOI18N
        AppIcon.setText("Image");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("The Hoteliers");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Welcome to, Hotel Sinjara");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(AppIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(14, 14, 14))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AppIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19))
                .addGap(14, 14, 14))
        );

        sidePanel.setBackground(new java.awt.Color(45, 53, 69));
        sidePanel.setAlignmentX(0.0F);
        sidePanel.setAlignmentY(0.0F);

        HomeButton.setBackground(new java.awt.Color(45, 53, 69));
        HomeButton.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(255, 255, 255));
        HomeButton.setText("Home");
        HomeButton.setBorder(null);
        HomeButton.setContentAreaFilled(false);
        HomeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeButton.setFocusPainted(false);
        HomeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        BookingButton.setBackground(new java.awt.Color(45, 53, 69));
        BookingButton.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        BookingButton.setForeground(new java.awt.Color(89, 95, 239));
        BookingButton.setText("Bookings");
        BookingButton.setBorder(null);
        BookingButton.setContentAreaFilled(false);
        BookingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookingButton.setFocusPainted(false);
        BookingButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BookingButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingButtonActionPerformed(evt);
            }
        });

        CustomerButton.setBackground(new java.awt.Color(45, 53, 69));
        CustomerButton.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        CustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        CustomerButton.setText("Customers");
        CustomerButton.setBorder(null);
        CustomerButton.setContentAreaFilled(false);
        CustomerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CustomerButton.setFocusPainted(false);
        CustomerButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CustomerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerButtonActionPerformed(evt);
            }
        });

        PaymentButton.setBackground(new java.awt.Color(45, 53, 69));
        PaymentButton.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        PaymentButton.setForeground(new java.awt.Color(255, 255, 255));
        PaymentButton.setText("Rooms");
        PaymentButton.setBorder(null);
        PaymentButton.setContentAreaFilled(false);
        PaymentButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PaymentButton.setFocusPainted(false);
        PaymentButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PaymentButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentButtonActionPerformed(evt);
            }
        });

        EmployeeButton.setBackground(new java.awt.Color(45, 53, 69));
        EmployeeButton.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        EmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeButton.setText("Employees");
        EmployeeButton.setBorder(null);
        EmployeeButton.setContentAreaFilled(false);
        EmployeeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EmployeeButton.setFocusPainted(false);
        EmployeeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmployeeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeButtonActionPerformed(evt);
            }
        });

        SubmitButton2.setBackground(new java.awt.Color(255, 51, 0));
        SubmitButton2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SubmitButton2.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton2.setText("Log Out");
        SubmitButton2.setBorder(null);
        SubmitButton2.setBorderPainted(false);
        SubmitButton2.setContentAreaFilled(false);
        SubmitButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitButton2.setFocusPainted(false);
        SubmitButton2.setOpaque(true);
        SubmitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton2ActionPerformed(evt);
            }
        });

        SubmitButton5.setBackground(new java.awt.Color(89, 95, 239));
        SubmitButton5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SubmitButton5.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton5.setText("Update Password");
        SubmitButton5.setBorder(null);
        SubmitButton5.setBorderPainted(false);
        SubmitButton5.setContentAreaFilled(false);
        SubmitButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitButton5.setFocusPainted(false);
        SubmitButton5.setOpaque(true);
        SubmitButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubmitButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EmployeeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addComponent(PaymentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CustomerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BookingButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HomeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubmitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(BookingButton)
                .addGap(40, 40, 40)
                .addComponent(CustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(PaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(EmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(SubmitButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubmitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 53, 69));
        jLabel1.setText("New Booking");

        CenterPanel.setBackground(new java.awt.Color(242, 242, 242));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(112, 112, 112));
        jLabel9.setText("Customer's Name ");

        cust_name.setBackground(new java.awt.Color(255, 255, 255));
        cust_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cust_name.setForeground(new java.awt.Color(112, 112, 112));
        cust_name.setText("Shreeyash Haritashya");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(112, 112, 112));
        jLabel11.setText("Customer's ID");

        checkin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkin.setForeground(new java.awt.Color(112, 112, 112));
        checkin.setBorder(null);
        checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Enter Date in YYYY-MM-DD format");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(112, 112, 112));
        jLabel12.setText("Check-Out Date");

        checkout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        checkout.setForeground(new java.awt.Color(112, 112, 112));
        checkout.setBorder(null);
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Enter Date in YYYY-MM-DD format");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(112, 112, 112));
        jLabel13.setText("Check-In Date");

        amount.setBackground(new java.awt.Color(255, 255, 255));
        amount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        amount.setForeground(new java.awt.Color(112, 112, 112));
        amount.setText("4000 INR");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(112, 112, 112));
        jLabel15.setText("Number of Rooms");

        type.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        type.setForeground(new java.awt.Color(112, 112, 112));
        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Triple", "Quad", "Queen", "King" }));
        type.setBorder(null);
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(112, 112, 112));
        jLabel16.setText("Room Type");

        num.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        num.setForeground(new java.awt.Color(112, 112, 112));
        num.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        num.setBorder(null);

        SubmitButton1.setBackground(new java.awt.Color(87, 184, 148));
        SubmitButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        SubmitButton1.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton1.setText("Generate Amount");
        SubmitButton1.setBorder(null);
        SubmitButton1.setBorderPainted(false);
        SubmitButton1.setContentAreaFilled(false);
        SubmitButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitButton1.setFocusPainted(false);
        SubmitButton1.setOpaque(true);
        SubmitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton1ActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(112, 112, 112));
        jLabel17.setText("Amount");

        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id.setForeground(new java.awt.Color(112, 112, 112));
        id.setText("01296");

        SubmitButton3.setBackground(new java.awt.Color(87, 184, 148));
        SubmitButton3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        SubmitButton3.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton3.setText("Check Out");
        SubmitButton3.setBorder(null);
        SubmitButton3.setBorderPainted(false);
        SubmitButton3.setContentAreaFilled(false);
        SubmitButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitButton3.setFocusPainted(false);
        SubmitButton3.setOpaque(true);
        SubmitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CenterPanelLayout = new javax.swing.GroupLayout(CenterPanel);
        CenterPanel.setLayout(CenterPanelLayout);
        CenterPanelLayout.setHorizontalGroup(
            CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(CenterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CenterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(87, 87, 87)
                        .addComponent(checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CenterPanelLayout.createSequentialGroup()
                        .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CenterPanelLayout.createSequentialGroup()
                                .addComponent(amount)
                                .addGap(10, 10, 10)
                                .addComponent(SubmitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CenterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(CenterPanelLayout.createSequentialGroup()
                        .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CenterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CenterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(53, 53, 53)))
                        .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cust_name)
                            .addComponent(id))
                        .addGap(72, 72, 72))
                    .addComponent(SubmitButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        CenterPanelLayout.setVerticalGroup(
            CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cust_name))
                .addGap(25, 25, 25)
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(id))
                .addGap(25, 25, 25)
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(amount)
                    .addComponent(SubmitButton1))
                .addGap(30, 30, 30)
                .addComponent(SubmitButton3)
                .addGap(20, 20, 20))
        );

        emp_name_detail.setBackground(new java.awt.Color(255, 255, 255));
        emp_name_detail.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        emp_name_detail.setForeground(new java.awt.Color(112, 112, 112));
        emp_name_detail.setText("Shayam Singh");

        emp_name_label.setBackground(new java.awt.Color(255, 255, 255));
        emp_name_label.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        emp_name_label.setForeground(new java.awt.Color(112, 112, 112));
        emp_name_label.setText("Employee Name -");

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(112, 112, 112));
        jLabel26.setText("ID -");

        emp_id_detail.setBackground(new java.awt.Color(255, 255, 255));
        emp_id_detail.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        emp_id_detail.setForeground(new java.awt.Color(112, 112, 112));
        emp_id_detail.setText("10235");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CenterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(558, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(emp_name_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emp_name_detail)
                            .addComponent(emp_id_detail))
                        .addGap(14, 14, 14))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emp_name_label)
                            .addComponent(emp_name_detail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(emp_id_detail))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(CenterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        NewBooking.this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void BookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingButtonActionPerformed
        NewBooking.this.setVisible(false);
        new Bookings().setVisible(true);
        
    }//GEN-LAST:event_BookingButtonActionPerformed

    private void CustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerButtonActionPerformed
        NewBooking.this.setVisible(false);
        new Customers().setVisible(true);
    }//GEN-LAST:event_CustomerButtonActionPerformed

    private void PaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentButtonActionPerformed
        NewBooking.this.setVisible(false);
        new Rooms().setVisible(true);
    }//GEN-LAST:event_PaymentButtonActionPerformed

    private void EmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeButtonActionPerformed
        NewBooking.this.setVisible(false);
        new Employees().setVisible(true);
    }//GEN-LAST:event_EmployeeButtonActionPerformed

    private void SubmitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton2ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?autoReconnect=true&useSSL=false", "root", "aman123456");
            Statement st = con.createStatement();
            String r = "delete from logged_in_hotel_id";
            st.executeUpdate(r);
            NewBooking.this.setVisible(false);
            new LogInPage().setVisible(true);
        } catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_SubmitButton2ActionPerformed

    private void SubmitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton1ActionPerformed
           String check_in = checkin.getText();
           String check_out = checkout.getText();
           String r_type = (String)type.getSelectedItem();
           int n_rooms = Integer.parseInt((String) num.getSelectedItem());
           try{
              Date c1 = new SimpleDateFormat("yyyy-mm-dd").parse(check_in);
              Date c2 = new SimpleDateFormat("yyyy-mm-dd").parse(check_out);
              long diff = c2.getTime() - c1.getTime();
              int days = (int) Math.ceil((diff / (1000*60*60*24)));
              
              switch(r_type){
                  case "Single":
                      int total = n_rooms*days*1000;
                      amount.setText(Integer.toString(total));
                      break;
                  case "Double":
                      int total1 = n_rooms*days*2000;
                      amount.setText(Integer.toString(total1));
                      break;
                  case "Triple":
                      int total2 = n_rooms*days*3000;
                      amount.setText(Integer.toString(total2));
                      break;
                  case "Quad":
                      int total3 = n_rooms*days*4000;
                      amount.setText(Integer.toString(total3));
                      break;
                  case "Queen":
                      int total4 = n_rooms*days*5000;
                      amount.setText(Integer.toString(total4));
                      break;
                  case "King":
                      int total5 = n_rooms*days*6000;
                      amount.setText(Integer.toString(total5));
                      break; 
              }
              SubmitButton3.setVisible(true);
           } catch (Exception e){
               System.out.print(e);
           }
    }//GEN-LAST:event_SubmitButton1ActionPerformed

    private void checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkinActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkoutActionPerformed

    private void SubmitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton3ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/hms?autoReconnect=true&useSSL=false", "root", "aman123456");
            Statement st = con.createStatement();
            String r_type = (String)type.getSelectedItem();
            String r = "select * from rooms where room_type = '"+ r_type +"' and room_status = 'v' ";
            ResultSet rs = st.executeQuery(r);
            if(rs.next()){
                String hotel_id = null;
                String r1 = "select id from logged_in_hotel_id where id is not null";
                ResultSet rs1 = st.executeQuery(r1);
                if(rs1.next()){
                    hotel_id = rs1.getString("id");
                    System.out.print(hotel_id);
                } else {
                    JOptionPane.showMessageDialog(null, "Can't Proceed, Hotel ID error");
                }
                
                String r2 = "insert into booking(book_cust_id, book_hotel_id, book_room_count, book_amount, check_in_date, check_out_date) values"
                        + "('"+ id.getText() +"', '"+ hotel_id +"', '"+ (String) num.getSelectedItem() +"', '"+ amount.getText() +"', '"+ checkin.getText() +"', '"+ checkout.getText() +"')";
                int rs2 = st.executeUpdate(r2);
                
                r2 = "select book_id from booking order by book_id desc limit 1";
                ResultSet rs4 = st.executeQuery(r2);
                
                if(rs4.next()){
                    String book_id = rs4.getString("book_id");
                    r = "update rooms set room_status = 'e', room_book_id = '"+ book_id +"' where not room_status = 'e' and room_id = (select room_id from (select * from rooms) as room where room_type = '"+ type.getSelectedItem() +"' limit 1)";
                    int rs3 = st.executeUpdate(r);
                    JOptionPane.showMessageDialog(null, "Booking made successfully!");
                    NewBooking.this.setVisible(false);
                    new Bookings().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Room Entry Error!");
                }   
            } else {
                JOptionPane.showMessageDialog(null, "No room available for desired type! Change the room type");
            }
        } catch(Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_SubmitButton3ActionPerformed

    private void SubmitButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton5ActionPerformed
        new UpdatePassword().setVisible(true);
    }//GEN-LAST:event_SubmitButton5ActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppIcon;
    private javax.swing.JButton BookingButton;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JButton CustomerButton;
    private javax.swing.JButton EmployeeButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton PaymentButton;
    private javax.swing.JButton SubmitButton1;
    private javax.swing.JButton SubmitButton2;
    private javax.swing.JButton SubmitButton3;
    private javax.swing.JButton SubmitButton5;
    private javax.swing.JLabel amount;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField checkin;
    private javax.swing.JTextField checkout;
    private javax.swing.JLabel cust_name;
    private javax.swing.JLabel emp_id_detail;
    private javax.swing.JLabel emp_name_detail;
    private javax.swing.JLabel emp_name_label;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox num;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
